/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bvakili.portlet.integration.box.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BoxToken service. Represents a row in the &quot;BoxToken&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bvakili.portlet.integration.box.model.impl.BoxTokenModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bvakili.portlet.integration.box.model.impl.BoxTokenImpl}.
 * </p>
 *
 * @author Bijan Vakili
 * @see BoxToken
 * @see com.bvakili.portlet.integration.box.model.impl.BoxTokenImpl
 * @see com.bvakili.portlet.integration.box.model.impl.BoxTokenModelImpl
 * @generated
 */
public interface BoxTokenModel extends AuditedModel, BaseModel<BoxToken> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a box token model instance should use the {@link BoxToken} interface instead.
	 */

	/**
	 * Returns the primary key of this box token.
	 *
	 * @return the primary key of this box token
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this box token.
	 *
	 * @param primaryKey the primary key of this box token
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the box token ID of this box token.
	 *
	 * @return the box token ID of this box token
	 */
	public long getBoxTokenId();

	/**
	 * Sets the box token ID of this box token.
	 *
	 * @param boxTokenId the box token ID of this box token
	 */
	public void setBoxTokenId(long boxTokenId);

	/**
	 * Returns the company ID of this box token.
	 *
	 * @return the company ID of this box token
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this box token.
	 *
	 * @param companyId the company ID of this box token
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this box token.
	 *
	 * @return the user ID of this box token
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this box token.
	 *
	 * @param userId the user ID of this box token
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this box token.
	 *
	 * @return the user uuid of this box token
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this box token.
	 *
	 * @param userUuid the user uuid of this box token
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this box token.
	 *
	 * @return the user name of this box token
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this box token.
	 *
	 * @param userName the user name of this box token
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this box token.
	 *
	 * @return the create date of this box token
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this box token.
	 *
	 * @param createDate the create date of this box token
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this box token.
	 *
	 * @return the modified date of this box token
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this box token.
	 *
	 * @param modifiedDate the modified date of this box token
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the access token of this box token.
	 *
	 * @return the access token of this box token
	 */
	@AutoEscape
	public String getAccessToken();

	/**
	 * Sets the access token of this box token.
	 *
	 * @param accessToken the access token of this box token
	 */
	public void setAccessToken(String accessToken);

	/**
	 * Returns the refresh token of this box token.
	 *
	 * @return the refresh token of this box token
	 */
	@AutoEscape
	public String getRefreshToken();

	/**
	 * Sets the refresh token of this box token.
	 *
	 * @param refreshToken the refresh token of this box token
	 */
	public void setRefreshToken(String refreshToken);

	/**
	 * Returns the access token expiration of this box token.
	 *
	 * @return the access token expiration of this box token
	 */
	public long getAccessTokenExpiration();

	/**
	 * Sets the access token expiration of this box token.
	 *
	 * @param accessTokenExpiration the access token expiration of this box token
	 */
	public void setAccessTokenExpiration(long accessTokenExpiration);

	/**
	 * Returns the refresh token expiration of this box token.
	 *
	 * @return the refresh token expiration of this box token
	 */
	public long getRefreshTokenExpiration();

	/**
	 * Sets the refresh token expiration of this box token.
	 *
	 * @param refreshTokenExpiration the refresh token expiration of this box token
	 */
	public void setRefreshTokenExpiration(long refreshTokenExpiration);

	/**
	 * Returns the callback u r l of this box token.
	 *
	 * @return the callback u r l of this box token
	 */
	@AutoEscape
	public String getCallbackURL();

	/**
	 * Sets the callback u r l of this box token.
	 *
	 * @param callbackURL the callback u r l of this box token
	 */
	public void setCallbackURL(String callbackURL);

	/**
	 * Returns the expired of this box token.
	 *
	 * @return the expired of this box token
	 */
	public boolean getExpired();

	/**
	 * Returns <code>true</code> if this box token is expired.
	 *
	 * @return <code>true</code> if this box token is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Sets whether this box token is expired.
	 *
	 * @param expired the expired of this box token
	 */
	public void setExpired(boolean expired);

	/**
	 * Returns the repository ID of this box token.
	 *
	 * @return the repository ID of this box token
	 */
	public long getRepositoryId();

	/**
	 * Sets the repository ID of this box token.
	 *
	 * @param repositoryId the repository ID of this box token
	 */
	public void setRepositoryId(long repositoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BoxToken boxToken);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BoxToken> toCacheModel();

	@Override
	public BoxToken toEscapedModel();

	@Override
	public BoxToken toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}